//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafkaInfrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KafkaInfrastructure.Resources.InfoMessages", typeof(InfoMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned partitions: [{0}].
        /// </summary>
        internal static string AssignedPartitions {
            get {
                return ResourceManager.GetString("AssignedPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing consumer.
        /// </summary>
        internal static string ClosingConsumer {
            get {
                return ResourceManager.GetString("ClosingConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were commited messages of : {0}, partition {1}, till offset {2}..
        /// </summary>
        internal static string CommitedMessages {
            get {
                return ResourceManager.GetString("CommitedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating consumer for {0}.
        /// </summary>
        internal static string CreatingConsumer {
            get {
                return ResourceManager.GetString("CreatingConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered &apos;{0}&apos; to: {1}.
        /// </summary>
        internal static string DeliveredMessage {
            get {
                return ResourceManager.GetString("DeliveredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing schema registry.
        /// </summary>
        internal static string DisposingSchemaRegistry {
            get {
                return ResourceManager.GetString("DisposingSchemaRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached end of topic {0}, partition {1}, offset {2}.
        /// </summary>
        internal static string ReachedEndOfTopic {
            get {
                return ResourceManager.GetString("ReachedEndOfTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received message at {0}: {1}.
        /// </summary>
        internal static string ReceivedMessage {
            get {
                return ResourceManager.GetString("ReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoking assignment: [{0}].
        /// </summary>
        internal static string RevokingAssignment {
            get {
                return ResourceManager.GetString("RevokingAssignment", resourceCulture);
            }
        }
    }
}
