trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Solution/ApiSvc/*

parameters:
- name: ContainerRegistryServer
  type: string
  default: Kanya Fields Docker Hub

extends:
  template: Templates/publish-image-pipeline-template.yaml
  parameters:
    ContainerRegistryServer: ${{ parameters.ContainerRegistryServer }}
    ProjectFolder: Solution/ApiSvc/ApiSvc
    ImageName: kf.apisvc
    ServiceFolder: Solution/ApiSvc