apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-passwordmediatorsvc-deployment
spec:
  selector:
    matchLabels:
      app: passwordmediatorsvc
  template:
    metadata:
      name: passwordmediatorsvc
      labels:
        app: passwordmediatorsvc
    spec:
      containers:
      - image: ${CONTAINER_REGISTRY_SERVER}/${PASSWORDMEDIATORSVC_IMAGE}
        name: passwordmediatorsvc-container
        imagePullPolicy: Always
        env:
        - name: CONSUMER_GROUP_ID
          value: PasswordMediatorSvcGroup
