apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-passwordmediatorsvc-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: passwordmediatorsvc-container
        env:
        - name: KAFKA_SERVICE_HOST
          value: kafka.dev.svc.cluster.local
        - name: KAFKA_SERVICE_PORT
          value: "9092"
        - name: SR_SCHEMA_REGISTRY_SERVICE_HOST
          value: schemaregistry-schema-registry
        - name: SR_SCHEMA_REGISTRY_SERVICE_PORT
          value: "8081"
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_PORT
          value: "6379"
